export const MOCK_FILMS = [
    {
        id: 1,
        movieName: 'Ready_1_1',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Ready_1_1.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 2,
        movieName: 'Ready_1_2',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Ready_1_2.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 3,
        movieName: 'Ready_1_3',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Ready_1_3.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 4,
        movieName: 'Ready_1_4',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Ready_1_4.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 5,
        movieName: 'Go_Diving_Fish1',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish1.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 6,
        movieName: 'Go_Diving_Fish2',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish2.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 7,
        movieName: 'Go_Diving_Fish3',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish3.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 8,
        movieName: 'Go_Diving_Fish4',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish4.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 9,
        movieName: 'Go_Diving_Fish5',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish5.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 10,
        movieName: 'Go_Diving_Fish6',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish6.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 11,
        movieName: 'Go_Diving_Fish7',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish7.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 12,
        movieName: 'Go_Diving_Fish8',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish8.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 13,
        movieName: 'Go_Diving_Fish9',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish9.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 14,
        movieName: 'Go_Diving_Fish10',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish10.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 15,
        movieName: 'Go_Diving_Fish11',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish11.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 16,
        movieName: 'Go_Diving_Fish12',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish12.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 17,
        movieName: 'Go_Diving_Fish13',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish13.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 18,
        movieName: 'Go_Diving_Fish14',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish14.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 19,
        movieName: 'Go_Diving_Fish15',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish15.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 20,
        movieName: 'Go_Diving_Fish16',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish16.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 21,
        movieName: 'Go_Diving_Fish17',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish17.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 22,
        movieName: 'Go_Diving_Fish18',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish18.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 23,
        movieName: 'Go_Diving_Fish19',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish19.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 24,
        movieName: 'Go_Diving_Fish20',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish20.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 25,
        movieName: 'Go_Diving_Fish21',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish21.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 26,
        movieName: 'Go_Diving_Fish22',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish22.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 27,
        movieName: 'Go_Diving_Fish23',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish23.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 28,
        movieName: 'Go_Diving_Fish24',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish24.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 29,
        movieName: 'Go_Diving_Fish25',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish25.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 30,
        movieName: 'Go_Diving_Fish26',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish26.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 31,
        movieName: 'Go_Diving_Fish27',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish27.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 32,
        movieName: 'Go_Diving_Fish28',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish28.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 33,
        movieName: 'Go_Diving_Fish29',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish29.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    },
    {
        id: 34,
        movieName: 'Go_Diving_Fish30',
        imgUrl: 'assets/img/14-07-2021-Alexandr/Go_Diving_Fish30.JPG',
        releaseYear: 2021,
        favorite: false,
        description: 'The best foto ever!',
    }
];